[helpers]

[default]
depends = []

[default.files]
"wezterm/wezterm.lua" = "~/.config/wezterm/wezterm.lua"
"powershell/Microsoft.PowerShell_profile.ps1" = "~/Documents/PowerShell/Microsoft.PowerShell_profile.ps1"

[default.variables]

# Package FNM (Fast Node Manager)
[fnm]
depends = []

[fnm.files]
"fnm/fnm-init.ps1" = "~/.config/powershell/fnm-init.ps1"

[fnm.variables]

[settings]
default_target_type = "automatic"
